### ISSUE TITLE
Sección Diseño de la solución

### ISSUE THREAD

**Issue by RoberG** [RoberG/AIVA-Reconocimiento-de-crotales#37]
- [x] Diagrama UML de Clases. #38 
- [x] Texto explicativo del diagrama UML de Clases. #39
- [x] Diagrama UML de Secuencia. #40
- [x] Texto explicativo del diagrama UML de Secuencia. #41
- [x] Texto explicativo sobre los algoritmos con UMLs de Actividad. #42
