### ISSUE TITLE
Redactar documentación

### ISSUE THREAD

**Issue by RoberG** [RoberG/AIVA-Reconocimiento-de-crotales#6]
- [x] Redactar sección "La visión" #4 

- [x] Redactar sección de "Descripción amplia y poco profunda" #5 

- [x] Redactar la planificación de tareas #22
