### ISSUE TITLE
Crear aplicación web

### ISSUE THREAD

**Issue by sariogonfer** [RoberG/AIVA-Reconocimiento-de-crotales#63]
- [x] Implementar  Front-end #64
- [x] Implementar Back-end #65
- [x] Configurar servidor wsgi #66
