### ISSUE TITLE
Desarrollar tests unitarios

### ISSUE THREAD

**Issue by sariogonfer** [RoberG/AIVA-Reconocimiento-de-crotales#7]
Leer ficheros:
- [x] Test: Leer jpg #11 
- [x] Test: Leer tif #12 
- [x] Test: Validar imagen #13 

Identificar crotal:
- [x] Test: Extraer cifras del crotal #8 
- [x] Test: Leer cifrar #9 
- [x] Test: Validar crotal #10
